-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, r.rest_avg SCORE
FROM (SELECT REST_ID, round(avg(REVIEW_SCORE), 2) rest_avg
      FROM REST_REVIEW
      GROUP BY REST_ID) r, REST_INFO i
WHERE r.REST_ID	 = i.REST_ID
AND i.ADDRESS LIKE '서울%'
ORDER BY 6 DESC, 4 DESC;