-- 코드를 입력하세요
SELECT 
    EXTRACT(year from o.SALES_DATE) YEAR, 
    EXTRACT(month from o.SALES_DATE) MONTH, 
    u.GENDER GENDER,
    count(DISTINCT u.USER_ID)
FROM USER_INFO u, ONLINE_SALE o
WHERE u.USER_ID = o.USER_ID
AND u.GENDER IS NOT NULL
GROUP BY EXTRACT(year from o.SALES_DATE), EXTRACT(month from o.SALES_DATE), u.GENDER
ORDER BY 1, 2, 3;