-- 코드를 입력하세요
SELECT 
    EXTRACT(year FROM o.SALES_DATE) YEAR, 
    EXTRACT(MONTH FROM o.SALES_DATE) MONTH,
    COUNT(DISTINCT o.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = 2021), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE o, (SELECT *
                     FROM USER_INFO 
                     WHERE JOINED >= TO_DATE('2021-01-01', 'yyyy-mm-dd') 
                     AND JOINED < TO_DATE('2022-01-01', 'yyyy-mm-dd')) u
WHERE u.USER_ID = o.USER_ID
GROUP BY EXTRACT(year FROM o.SALES_DATE), EXTRACT(month FROM o.SALES_DATE)
ORDER BY 1, 2;