-- 코드를 입력하세요
SELECT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(PRICE * AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE p.PRODUCT_ID = o.PRODUCT_ID
AND TO_CHAR(o.PRODUCE_DATE, 'yyyy-mm') = '2022-05'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY 3 DESC, 1;