SELECT 
    distinct h.HISTORY_ID, 

    case
        WHEN END_DATE - START_DATE + 1 BETWEEN 7 AND 29 then (DAILY_FEE * (END_DATE - START_DATE + 1))* 0.95
        WHEN END_DATE - START_DATE + 1 BETWEEN 30 AND 89 then (DAILY_FEE * (END_DATE - START_DATE + 1))* 0.92
        WHEN END_DATE - START_DATE + 1 >= 90 then (DAILY_FEE * (END_DATE - START_DATE + 1))* 0.85
        ELSE (DAILY_FEE * (END_DATE - START_DATE + 1))
    END FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_RENTAL_HISTORY h, CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
WHERE c.CAR_ID = h.CAR_ID
AND c.CAR_TYPE = d.CAR_TYPE
AND c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;