-- 코드를 입력하세요
SELECT DISTINCT r.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR r, CAR_RENTAL_COMPANY_RENTAL_HISTORY h
WHERE r.CAR_ID = h.CAR_ID
AND r.car_type = '세단'
AND to_char(h.start_date, 'mm') = '10'
ORDER BY 1 DESC;