-- 코드를 입력하세요
SELECT f1.CATEGORY, f1.MAX_PRICE, f2.PRODUCT_NAME
FROM (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
      FROM FOOD_PRODUCT 
      GROUP BY CATEGORY
      HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
      ORDER BY 2 DESC) f1, FOOD_PRODUCT f2
WHERE f1.CATEGORY = f2.CATEGORY
AND f1.MAX_PRICE = f2.PRICE
ORDER BY 2 DESC;